# Generated by Django 3.2.8 on 2021-11-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=500)),
                ('course_yearInCareer', models.IntegerField()),
                ('course_topic', models.ImageField(upload_to='')),
                ('course_isActive', models.BooleanField(default=True)),
                ('course_correlative', models.ManyToManyField(related_name='_courses_course_course_correlative_+', to='courses.Course')),
                ('course_idCareer', models.ManyToManyField(to='career.Career')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
