# Generated by Django 3.2.8 on 2021-11-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_idProfessor',
            field=models.ManyToManyField(to='professor.Professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_itsCorrelativeOf',
            field=models.ManyToManyField(related_name='_courses_course_course_itsCorrelativeOf_+', to='courses.Course'),
        ),
    ]
