# Generated by Django 3.2.8 on 2021-11-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20211102_1135'),
        ('professor', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_correlative',
            field=models.ManyToManyField(related_name='_courses_course_course_correlative_+', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_idCareer',
            field=models.ManyToManyField(to='career.Career'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_idProfessor',
            field=models.ManyToManyField(to='professor.Professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_itsCorrelativeOf',
            field=models.ManyToManyField(related_name='_courses_course_course_itsCorrelativeOf_+', to='courses.Course'),
        ),
    ]
