# Generated by Django 3.2.8 on 2021-11-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('professor_name', models.CharField(max_length=20)),
                ('professor_lastName', models.CharField(max_length=20)),
                ('professor_rank', models.FloatField()),
                ('professor_isSupervisor', models.BooleanField()),
                ('professor_isActive', models.BooleanField(default=True)),
                ('professor_idCareer', models.ManyToManyField(to='career.Career')),
                ('professor_idCourses', models.ManyToManyField(to='courses.Course')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
            },
        ),
    ]
