# Generated by Django 3.2.8 on 2021-11-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_name', models.CharField(max_length=20)),
                ('professor_lastName', models.CharField(max_length=20)),
                ('professor_rank', models.FloatField()),
                ('professor_isSupervisor', models.BooleanField()),
                ('professor_isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
            },
        ),
    ]
