# Generated by Django 3.2.8 on 2021-11-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211114_1054'),
        ('career', '0001_initial'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='professor_idCareer',
            field=models.ManyToManyField(blank=True, to='career.Career'),
        ),
        migrations.AddField(
            model_name='professor',
            name='professor_idCourses',
            field=models.ManyToManyField(blank=True, to='courses.Course'),
        ),
    ]
