# Generated by Django 3.2.8 on 2021-11-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20211102_1135'),
        ('courses', '0002_auto_20211102_1135'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='professor_idCareer',
            field=models.ManyToManyField(default=1, to='career.Career'),
        ),
        migrations.AddField(
            model_name='professor',
            name='professor_idCourses',
            field=models.ManyToManyField(default=1, to='courses.Course'),
        ),
    ]
