# Generated by Django 3.2.8 on 2021-11-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_initial'),
        ('courses', '0002_initial'),
        ('professor', '0002_auto_20211101_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='professor_idCareer',
            field=models.ManyToManyField(default=1, null=True, to='career.Career'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professor_idCourses',
            field=models.ManyToManyField(default=1, null=True, to='courses.Course'),
        ),
    ]
