# Generated by Django 3.2.8 on 2021-11-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_auto_20211101_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='professor_idCareer',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='professor_idCourses',
        ),
    ]
