# Generated by Django 3.2.8 on 2021-11-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_remove_career_carrer_idcourses'),
        ('courses', '0002_initial'),
        ('professor', '0006_auto_20211101_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='professor_idCareer',
            field=models.ManyToManyField(default=1, null=True, to='career.Career'),
        ),
        migrations.AddField(
            model_name='professor',
            name='professor_idCourses',
            field=models.ManyToManyField(default=1, null=True, to='courses.Course'),
        ),
    ]
