# Generated by Django 3.2.8 on 2021-11-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrer_name', models.CharField(max_length=100)),
                ('carrer_description', models.CharField(max_length=500)),
                ('carrer_years', models.IntegerField()),
                ('carrer_programYear', models.IntegerField()),
                ('carrer_isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
            },
        ),
    ]
