# Generated by Django 3.2.8 on 2021-11-14 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211114_1054'),
        ('professor', '0002_auto_20211114_1055'),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='carrer_idCourses',
            field=models.ManyToManyField(blank=True, related_name='MTM_courses', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='career',
            name='carrer_idProfessor',
            field=models.ManyToManyField(blank=True, related_name='MTM_professor', to='professor.Professor'),
        ),
        migrations.AddField(
            model_name='career',
            name='carrer_idSupervisor',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='FK_Supervisor', to='professor.professor'),
            preserve_default=False,
        ),
    ]
