# Generated by Django 3.2.8 on 2021-11-01 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='carrer_idCourses',
        ),
    ]
