# Generated by Django 3.2.8 on 2021-11-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_auto_20211114_1055'),
        ('career', '0002_auto_20211114_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='carrer_idSupervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='FK_Supervisor', to='professor.professor'),
        ),
    ]
